# Generated by Django 5.2 on 2025-04-24 02:50

import django.db.models.deletion
import job.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('job_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Temporaty', 'Temporaty'), ('InternShip', 'Internship')], default='Permanent', max_length=20)),
                ('education', models.CharField(choices=[('Diploma', 'Diploma'), ('Bachelors', 'Bachelors'), ('Master', 'Master'), ('Phd', 'Phd')], default='Bachelors', max_length=20)),
                ('industry', models.CharField(choices=[('Business', 'Business'), ('IT', 'It'), ('DesignAndTextile', 'Designandtextile'), ('Banking', 'Banking'), ('Education', 'Education'), ('Telecommunication', 'Telecommunication'), ('Sales', 'Sales'), ('Others', 'Others')], default='Business', max_length=20)),
                ('experience', models.CharField(choices=[('NO_EXPERIENCE', 'No Experience'), ('ONE_YEAR', 'One Year'), ('TWO_YEAR', 'Two Year'), ('THREE_YEAR', 'Three Year'), ('FOUR_YEAR_PLUS', 'Four Year Plus')], default='NO_EXPERIENCE', max_length=20)),
                ('salary', models.IntegerField(default=1, null=True)),
                ('positions', models.IntegerField(default=1, null=True)),
                ('compnay', models.CharField(max_length=100, null=True)),
                ('last_date', models.DateField(default=job.models.return_date_time)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
